server:
  port: 8080

spring:
  application:
    name: ILO Community Energy Allocation
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DB_NAME}
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}

jwt:
  secret: ${JWT_KEY}
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 604800000
  reset-token:
    expiration: 3600000

resilience4j:
  circuitbreaker:
    instances:
      redis:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
      rateLimit:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
  retry:
    instances:
      redis:
        maxAttempts: 3
        waitDuration: 100ms
      rateLimit:
        maxAttempts: 3
        waitDuration: 100ms

rate-limit:
  capacity: 100
  duration: 1m
cache:
  ttl:
    energyPrices: 60m
    energySources: 30m
    userPreferences: 15m


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    defaultModelsExpandDepth: -1
  info:
    title: ILO Community Energy Allocation API
    version: 1.0.0
    description: API documentation for the ILO Community Energy Allocation system
    contact:
      name: Development Team
      email: dev@ilo.com
