server:
  port: 8080

spring:
  application:
    name: ILO Community Energy Allocation
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      database: ${SPRING_DATA_MONGODB_DB_NAME}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_JWK_SET_URI}

jwt:
  secret: ${JWT_KEY}
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 604800000
  reset-token:
    expiration: 3600000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

---
spring:
  config:
    activate:
      on-profile: test
  data:
    mongodb:
      uri: mongodb://localhost:27017/testdb