name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: community-energy-allocation:${{ github.sha }}
      - name: Test Docker image
        run: |
          docker images
          docker run -d --name test-container community-energy-allocation:${{ github.sha }}
          docker ps
          sleep 10
          docker logs test-container
          docker stop test-container
          docker rm test-container

# Deployment job commented out for PoC
#  deploy:
#    needs: docker
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - name: Deploy to Kubernetes
#      uses: azure/k8s-deploy@v1
#      with:
#        manifests: |
#          backend-deployment.yaml
#          mongodb-deployment.yaml
#      env:
#        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}